[package]
name = "Snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
imageproc = "0.23.0"
pixels = "0.9.0"
winit = "0.26.1"
winit_input_helper = "0.12.0"
rand = "0.8.5"
